import type { CreateFranchiseDTO, FranchiseStatus } from "./types.js";

export interface SeedFranchise extends CreateFranchiseDTO {
  status: FranchiseStatus;
}

export const SEED_FRANCHISES: SeedFranchise[] = [
  {
    name: "Franquia Centro SP",
    ownerName: "Carlos Eduardo Silva",
    email: "carlos.silva@franquiacentro.com.br",
    phone: "(11) 98765-4321",
    address: "Rua Augusta, 1500",
    city: "São Paulo",
    state: "SP",
    status: "active",
  },
  {
    name: "Franquia Copacabana",
    ownerName: "Ana Paula Oliveira",
    email: "ana.oliveira@franquiacopa.com.br",
    phone: "(21) 99876-5432",
    address: "Av. Atlântica, 3200",
    city: "Rio de Janeiro",
    state: "RJ",
    status: "active",
  },
  {
    name: "Franquia Savassi BH",
    ownerName: "Roberto Santos Filho",
    email: "roberto.santos@franquiasavassi.com.br",
    phone: "(31) 97654-3210",
    address: "Rua Pernambuco, 800",
    city: "Belo Horizonte",
    state: "MG",
    status: "active",
  },
  {
    name: "Franquia Batel Curitiba",
    ownerName: "Fernanda Mendes",
    email: "fernanda.mendes@franquiabatel.com.br",
    phone: "(41) 96543-2109",
    address: "Rua Batel, 1200",
    city: "Curitiba",
    state: "PR",
    status: "pending",
  },
  {
    name: "Franquia Moinhos POA",
    ownerName: "Gustavo Hartmann",
    email: "gustavo.hartmann@franquiamoinhos.com.br",
    phone: "(51) 95432-1098",
    address: "Rua Padre Chagas, 300",
    city: "Porto Alegre",
    state: "RS",
    status: "active",
  },
  {
    name: "Franquia Pituba Salvador",
    ownerName: "Luciana Reis Costa",
    email: "luciana.costa@franquiapituba.com.br",
    phone: "(71) 94321-0987",
    address: "Av. Paulo VI, 1000",
    city: "Salvador",
    state: "BA",
    status: "inactive",
  },
  {
    name: "Franquia Aldeota Fortaleza",
    ownerName: "Pedro Henrique Lima",
    email: "pedro.lima@franquiaaldeota.com.br",
    phone: "(85) 93210-9876",
    address: "Rua Torres Câmara, 450",
    city: "Fortaleza",
    state: "CE",
    status: "pending",
  },
  {
    name: "Franquia Adrianópolis Manaus",
    ownerName: "Mariana Souza Braga",
    email: "mariana.braga@franquiamanaus.com.br",
    phone: "(92) 92109-8765",
    address: "Av. Ephigênio Salles, 2000",
    city: "Manaus",
    state: "AM",
    status: "active",
  },
  {
    name: "Franquia Lago Sul Brasília",
    ownerName: "Thiago Almeida Rocha",
    email: "thiago.rocha@franquiabsb.com.br",
    phone: "(61) 91098-7654",
    address: "SHIS QI 9/11, Bloco A",
    city: "Brasília",
    state: "DF",
    status: "active",
  },
  {
    name: "Franquia Boa Viagem Recife",
    ownerName: "Juliana Ferreira Pinto",
    email: "juliana.pinto@franquiarecife.com.br",
    phone: "(81) 90987-6543",
    address: "Av. Boa Viagem, 4500",
    city: "Recife",
    state: "PE",
    status: "pending",
  },
];
